spring:
  profiles:
    default: dev
  mvc:
    hidden-method:
      filter:
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(plDde76MscNwKMt9v4A6Rw==)
    password: ENC(OH+qshDPtFh1h1gDdWExzz/t0BlOzVbo)
    url: ENC(L4aT4GfkEsf36RsmLcicmZmhfwgA7o3VTkq0GMSRBorX3d++tPdam9QXDcnR99LE+6YH3dImFev/dHPxJ1+l9++i2B8cg6IHw3Y508pY/zARtnynx6yle453gCfUJkYAzBH2kEtzTeB7cyEvXiXqUIkVgOevG6NMOk3Eth8Kroib8xkHWpFNOOWnSt72b7dC)

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(EnGEuiNi8se1PXYrqy+PxI2vcLBn3DGx)
    password: ENC(cqAYQgTmw7Ze3I5X+tqACkP8Ai5vr+DCPvV9cv8n2uk=)
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true



  security:
    oauth2:
      client:
        registration:

          naver:
            client-id: ENC(0ryhL75ty9DPzpCm3xR9h0xxOGYBddlHBb3l//6kPHk=)
            client-secret: ENC(yP4oKUUrldyaMwy1xYVNNn5bumB052Zm)
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, profile_image
            client-name: Naver
          kakao:
            clientId: ENC(v3HCSehY14ighRx423yYdd0c+9lPu14JXCBJBcMLKDcZWKRPmCyo5xlYrh9lmr4B)
            scope: friends, talk_message, account_email, profile_nickname, profile_image
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

#  thymeleaf:
#    cache: false
#    prefix: file:src/main/resources/templates/
#    devtools:
#      livereload:
#        enabled: true
#      restart:
#        enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 10
        format_sql: true
        show_sql: true

logging.level:
  org.hibernate:
    SQL: debug
    orm.jdbc.bind: trace


### custom ###
jasypt:
  encryptor:
    bean: jasyptStringEncryptor


scheduler:
  cron:
    member: "0 */3 * * * *"
    study: "0 */5 * * * *"

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

