spring:
  profiles:
    default:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(luN+bf0w1R9g5anC4KUI2g==)
    password: ENC(KfmWnoG7NkR7Dp+RknWqIiIqLshebRLb)
    url: ENC(Cx/IXKOxUZD0I2Of1dWROE7qNptdfamGeGNDc9Lth5GUAzKsE4mdEff6fG/CDOLNdAbLKSu3lzz4PR+8zL2lgRO1xp+oHXboaTamXLrJygM9HR4wqS5HtSJEAB+3bThhTvug7rklMOQnC9OHSlwEiaVDUDZacCLl7t/NP40Sb9zEifGKtx1mTA==)

  security:
    oauth2:
      client:
        registration:

          naver:
            client-id: ENC(0ryhL75ty9DPzpCm3xR9h0xxOGYBddlHBb3l//6kPHk=)
            client-secret: ENC(yP4oKUUrldyaMwy1xYVNNn5bumB052Zm)
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, profile_image
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
    devtools:
      livereload:
        enabled: true
      restart:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging.level:
  org.hibernate:
    SQL: debug
    #    type: trace # (Spring boot 2.X.X)
    orm.jdbc.bind: trace # (Spring boot 3.X.X)
jasypt:
  encryptor:
    bean: jasyptStringEncryptor